image:
  - Visual Studio 2017
  - Ubuntu

stack: jdk 8
environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  CLIENTTESTS_ARTIFACTORY_URL:
    secure: RIh0gGFDn2JAnLUEEqLsQj2LHpPj3KIjKiRyPeN4nT8Yxi5imzLTTJAGZaCz/DpM
  CLIENTTESTS_ARTIFACTORY_USERNAME:
    secure: YEB5Wiv9a2vNpUhy+MfL+A==
  CLIENTTESTS_ARTIFACTORY_PASSWORD:
    secure: Um8o75MQIieSavIemF4ySA==

test_script:
  - sh: ./gradlew test
  - cmd: gradlew.bat test

# Don't actually build.
build: off

cache:
  - C:\Users\appveyor\.gradle\ -> build.gradle
  - /home/appveyor/.gradle/ -> build.gradle